spring:
    application:
        name: sritel-services
    data:
        mongodb:
            uri: mongodb+srv://jayathilakeravishan:Pq5OcwI88iJhXjDe@customer.od53w.mongodb.net/sritel-services

server:
    port: 9001
