services:
  config-server:
    build: ./Services/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - sritel-network

  discovery-server:
    build:
      context: ./Services/discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8761
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    networks:
      - sritel-network

  api-gateway:
    build: 
      context: ./Services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - SERVER_PORT=8222
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "8223:8222"
    networks:
      - sritel-network

  sritel-service:
    build:
      context: ./Services/sritel-services
      dockerfile: Dockerfile
    container_name: sritel-service
    environment:
      - SERVER_PORT=9010
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "9010:9010"
    networks:
      - sritel-network


  billing-service:
    build:
      context: ./Services/billing
      dockerfile: Dockerfile
    container_name: billing-service
    environment:
      - SERVER_PORT=9000
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "9000:9000"
    networks:
      - sritel-network

  customer-service:
    build:
      context: ./Services/customer
      dockerfile: Dockerfile
    container_name: customer-service
    environment:
      - SERVER_PORT=8090
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "8090:8090"
    networks:
      - sritel-network

  payment-service:
    build:
      context: ./Services/payment
      dockerfile: Dockerfile
    container_name: payment-service
    environment:
      - SERVER_PORT=8099
    depends_on:
      - config-server
      - discovery-server  
    ports:
      - "8099:8099"
    networks:
      - sritel-network

  pub-sub:
    build:
      context: ./Services/pub-sub
      dockerfile: Dockerfile
    container_name: pub-sub
    environment:
      - SERVER_PORT=8989
    depends_on:
      - config-server
      - discovery-server  
      - kafka
      - zookeeper
    ports:
      - "8989:8989"
    networks:
      - sritel-network

  smtp-mail-server:
    build:
      context: ./Services/smtp-mail-server
      dockerfile: Dockerfile
    container_name: smtp-mail-server
    environment:
      - SERVER_PORT=8990
    depends_on:
      - config-server
      - discovery-server  
      - kafka
      - zookeeper
    ports:
      - "8990:8990"
    networks:
      - sritel-network

  

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - sritel-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - sritel-network

  webserver:
    image: caddy:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8222:80"
    volumes:
      - ./caddy-conf:/etc/caddy/
      - caddy-config:/config
      - caddy-data:/data
    networks:
      - sritel-network

volumes:
  caddy-config:
  caddy-data:
      


networks:
  sritel-network:
    driver: bridge

