services:
  config-server:
    build: ./Services/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - sritel-network

  discovery-server:
    build:
      context: ./Services/discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8761
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    networks:
      - sritel-network

  api-gateway:
    build: 
      context: ./Services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - eureka_client_serviceurl_defaultzone=EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVER_PORT=8222
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "8222:8222"
    networks:
      - sritel-network

  sritel-service:
    build:
      context: ./Services/sritel-services
      dockerfile: Dockerfile
    container_name: sritel-service
    environment:
      - eureka_client_serviceurl_defaultzone=EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVER_PORT=9010
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "9010:9010"
    networks:
      - sritel-network


  billing-service:
    build:
      context: ./Services/billing
      dockerfile: Dockerfile
    container_name: billing-service
    environment:
      - eureka_client_serviceurl_defaultzone=EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVER_PORT=9000
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "9000:9000"
    networks:
      - sritel-network

  customer-service:
    build:
      context: ./Services/customer
      dockerfile: Dockerfile
    container_name: customer-service
    environment:
      - eureka_client_serviceurl_defaultzone=http://discovery-server:8761/eureka
      - SERVER_PORT=8090
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "8090:8090"
    networks:
      - sritel-network

  payment-service:
    build:
      context: ./Services/payment
      dockerfile: Dockerfile
    container_name: payment-service
    environment:
      - eureka_client_serviceurl_defaultzone=EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SERVER_PORT=8099
    depends_on:
      - config-server
      - discovery-server  
    ports:
      - "8099:8099"
    networks:
      - sritel-network

      


networks:
  sritel-network:
    driver: bridge

