spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <insert email address here>
    password: <insert generated passkey here>
    properties:
      mail:
        smtp:
          auth: true
          starttls: enable
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-notification-group
      auto-offset-reset: earliest
    template:
      default-topic: billing-topic
