spring:
  data:
    mongodb:
      uri: mongodb+srv://jayathilakeravishan:Pq5OcwI88iJhXjDe@customer.od53w.mongodb.net/billing
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka