spring:
  data:
    mongodb:
      uri: mongodb+srv://jayathilakeravishan:Pq5OcwI88iJhXjDe@customer.od53w.mongodb.net/customer
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka