spring:
  data:
    mongodb:
      uri: mongodb+srv://sritel:sritel@cluster0.dzsjndd.mongodb.net/customer?retryWrites=true&w=majority&appName=sritel
      
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

