eureka:
  instance:
    hostname: eureka 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
      
server:
  port: 876