spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <email address here>
    password: <app password here>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: email-notification-group
      auto-offset-reset: earliest
    template:
      default-topic: billing-topic

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 8990