spring:
  data:
    mongodb:
      uri: mongodb+srv://sritel:sritel@cluster0.dzsjndd.mongodb.net/payment?retryWrites=true&w=majority&appName=sritel
server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka