spring:
    config:
        import: configserver:${CONFIGHOST}

    application:
        name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka   
    
